### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by albertgarcesb** [SAEEDStarv/xTGH#3]
Is there a way to disable Google Play restrictions with a module?

**Comment by aryanshojaei74** [comment]
سلام داداش سعید هیچ راهی پیدا نکردم باهات ارتباط برقرار کنم جز اینجا دمت گرم بخاطر برنامه های عالیت میخواستم بگم ممنون میشیم اینکه داری به خارجی ها کمک میکنی تیک تاک شون مود کنن برای کشور خودمونم ردیف کن ورژن جدیدو مرسی.

**Comment by Official-Mlx** [comment]
hey **thank** you
it was useful

**Comment by albertgarcesb** [comment]
> Hey. Describe the restriction.
